document.writeln("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">");
document.writeln("<html>");
document.writeln(" <head>");
document.writeln("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("  <title></title>");
document.writeln("  <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\"/>");
document.writeln("  <script language=\"javascript\" src=\"js/jquery-1.8.3.min.js\" type=\"text/javascript\"></script>");
document.writeln("  <script language=\"javascript\" src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>");
document.writeln(" </head>");
document.writeln(" <body >");
document.writeln("		<div style=\"margin-left:10px; margin-top:40px;\">");
document.writeln("			");
document.writeln("				<div>");
document.writeln("					<ul class=\"nav nav-tabs\">");
document.writeln("					  <li role=\"presentation\"><a href=\"queryVinInfo.html\" target=\"_top\">VIN信息查询</a></li>");
document.writeln("					  <li role=\"presentation\"><a href=\"queryServiceHandle.html\" target=\"_top\">Service Handle查询</a></li>");
document.writeln("					  <li role=\"presentation\"><a href=\"queryBidBinding.html\" target=\"_top\">BID/VIN绑定关系查询</a></li>");
document.writeln("					  <li role=\"presentation\"><a href=\"queryRingServerStatus.html\" target=\"_top\">振铃服务器可用性信息查询</a></li>");
document.writeln("					  <li role=\"presentation\"><a href=\"queryRingTaskLog.html\" target=\"_top\">振铃记录日志查询</a></li>");
document.writeln('					  <li role="presentation"><a href="basicRepo.html" target="_top">报表-终端活跃信息</a></li>');
document.writeln('					  <li role="presentation"><a href="#" onClick="waitforme"  target="_top">报表-设备存量</a></li>');
document.writeln('					  <li role="presentation"><a href="resolveTboxMessgae.html" onClick="waitforme"  target="_top">T-Box消息解析</a></li>');
document.writeln('					  <li role="presentation"><a href="tboxLog.html" onClick="waitforme"  target="_top">日志</a></li>');

document.writeln("					</ul>");
document.writeln("				</div>");
document.writeln("		</div>");
document.writeln(" </body>");
document.writeln("</html>");
document.writeln("");